services:
    FrostieDE\ComposerDependencyList\ComposerDependenciesResolver:
        arguments:
            - '%composer_dependency_list.lock_file%'

    FrostieDE\ComposerDependencyList\ComposerDependenciesResolverInterface: '@FrostieDE\ComposerDependencyList\ComposerDependenciesResolver'

    FrostieDE\ComposerDependencyListBundle\Controller\DefaultController:
        autowire: true
        autoconfigure: true
        arguments:
            $listTemplate: '%composer_dependency_list.list_template%'
            $licenseTemplate: '%composer_dependency_list.license_template%'
        tags: [ 'controller.service_arguments' ]

    FrostieDE\ComposerDependencyListBundle\Command\:
        resource: '../../Command'
        autowire: true
        autoconfigure: true
        tags: [ 'console.command' ]